to_do_list/urls.py
from django.urls import path

from to_do_list.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    task_toggle_done
)

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tasks/<int:pk>/toggle-done/", task_toggle_done, name="task-toggle-done"),

    path("tags", TagListView.as_view(), name="tag_list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "to_do_list"

to_do_list_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("to_do_list.urls", namespace="to_do_list"), name="home"),
]

to_do_list/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["done", "-created"]

    def __str__(self):
        formatted_created = self.created.strftime("%Y-%m-%d %H:%M:%S")
        return f"{self.content} - {formatted_created}({self.done})"

to_do_list/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from to_do_list.models import Task, Tag


class TaskListView(ListView):
    model = Task
    queryset = Task.objects.prefetch_related("tags")
    paginate_by = 3


class TaskCreateView(CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("to_do_list:index")


class TaskUpdateView(UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("to_do_list:index")


class TaskDeleteView(DeleteView):
    model = Task
    success_url = reverse_lazy("to_do_list:index")


class TagListView(ListView):
    model = Tag
    paginate_by = 5


class TagCreateView(CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("to_do_list:tag_list")


class TagUpdateView(UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("to_do_list:tag_list")


class TagDeleteView(DeleteView):
    model = Tag
    success_url = reverse_lazy("to_do_list:tag_list")


def task_toggle_done(request, pk):
    task = Task.objects.get(pk=pk)
    task.done = not task.done
    task.save()
    return HttpResponseRedirect(reverse_lazy("to_do_list:index"))

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>To Do List</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
        crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}{% endblock %}

      {% block pagination %}
        {% include "includes/pagination.html" %}
      {% endblock %}

    </div>
  </div>
</div>
</body>

</html>

templates/includes/create_update_form.html
<form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
</form>

templates/includes/delete_form.html
<form action="" method="post">
  {% csrf_token %}

  <input type="submit" value="Yes" class="btn btn-danger">
  <button type="button" class="btn btn-secondary" onclick="window.history.back();">
    Cancel
  </button>
</form>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'to_do_list:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'to_do_list:tag_list' %}">Tags</a></li>
</ul>

templates/to_do_list/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  {% include "includes/delete_form.html" %}
{% endblock %}

templates/to_do_list/tag_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  {% include "includes/create_update_form.html" %}
{% endblock %}

templates/to_do_list/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tags
    <a class="float-right btn btn-primary" href="{% url 'to_do_list:tag-create' %}">Add</a>
  </h1>
  
  <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.name }}
          </td>
          <td>
            <a class="btn btn-secondary" href="{% url 'to_do_list:tag-update' pk=tag.pk %}">Update</a>
          </td>
          <td>
            <a class="btn btn-secondary" href="{% url 'to_do_list:tag-delete' pk=tag.pk %}">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </table>
{% endblock %}

templates/to_do_list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  {% include "includes/delete_form.html" %}
{% endblock %}

templates/to_do_list/task_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  {% include "includes/create_update_form.html" %}
{% endblock %}

templates/to_do_list/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    TODO list
    <a class="float-right btn btn-primary" href="{% url 'to_do_list:task-create' %}">Add Task</a>
  </h1>


  {% for task in task_list %}
    <h4>
      {{ task.content }}
      {% if task.done %}
        <strong style="color: #00ca00">Done</strong>
        <a class="float-right btn btn-secondary" href="{% url 'to_do_list:task-toggle-done' pk=task.pk %}">Undo</a>
      {% else %}
        <strong style="color: #d10000">Not done</strong>
        <a class="float-right btn btn-primary" href="{% url 'to_do_list:task-toggle-done' pk=task.pk %}">Complete</a>
      {% endif %}
    </h4>
    <h6>
      Created: {{ task.created }}
      {% if task.deadline %}
        <span style="color: #950000">Deadline: {{ task.deadline }}</span>
      {% endif %}
    </h6>
    <h4>
      <strong style="color: #868c91">Tags: {{ task.tags.all|join:" " }}</strong>
      <a href="{% url 'to_do_list:task-update' pk=task.pk %}">Update</a>
      <a href="{% url 'to_do_list:task-delete' pk=task.pk %}">Delete</a>
    </h4>
    <hr>
  {% endfor %}
{% endblock %}